name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up python environment
      run: . set-up-python-venv.sh

    - name: Run linters and tests
      run: . venv/bin/activate && make test
